name: Start EC2 Server Manually

on:
  workflow_dispatch: # Manual trigger

jobs:
  start_ec2:
    runs-on: ubuntu-latest

    steps:
    - name: Check EC2 Instance State
      id: ec2_status
      run: |
        INSTANCE_ID="i-06aafe0ff7e642270" # Replace with your EC2 instance ID
        STATUS=$(aws ec2 describe-instances --instance-ids $INSTANCE_ID --query "Reservations[0].Instances[0].State.Name" --output text)
        echo "EC2 instance status: $STATUS"
        echo "::set-output name=instance_state::$STATUS"
        
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: "eu-west-2"

    - name: Start EC2 Instance If Not Running
      if: steps.ec2_status.outputs.instance_state != 'running'
      run: |
        INSTANCE_ID="i-06aafe0ff7e642270" # Replace with your EC2 instance ID
        aws ec2 start-instances --instance-ids $INSTANCE_ID
        echo "EC2 instance $INSTANCE_ID started successfully."
        
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: "eu-west-2"

    - name: Skip Start if Already Running
      if: steps.ec2_status.outputs.instance_state == 'running'
      run: |
        echo "EC2 instance is already running, no need to start."
